sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - secure: Ya3Kgiv0jW8riiZDwQ05+SYcU1KUPdeFUcdqiH7x1rbhkyM05F5bjYdRA8zo7j7xJcQDnfmQ/Yj4DK+Ugvagpl1pQbJnCUjpTiQmkNwKZYDCAVjw0RIYwmZgiwktsJgor1ykCvO0mr4pH4hKQeOEb2KP664Tpo8n2wFXqdLRYpVhGzY1Ot8LrPTHQqhUirZuQHZlkhFpJOS6Hf7lctryrFnLb5dSTBL6+x/P42UjhfL5rh8LACdY+dVmkt56ms3cbe85QiYK5qQkfB+Qn4kmhX6Ph35rCqDG9ipqT/G0vbCXCrq/asM2n7YMjW6jvuAHpJ3swRhb7qC6uzvY22jVFVhvqpY5W3Upa9fPTmQ8jhnGWbpjx2qNpSJNZxaByK5MVNh60MRSfWP+qbq6OPbY6k9luqr4CnFCnfnp/aE1UhBOAfEp1jizSR1aDKQqRdigl4izKIX22FWacjwSOrq3I5Jzsi/KBC+fd2tgAFwdDKM3FLFP28KMmvBtZZdFrduh0VQOe3UdGRGAwG+4c+hJrKpGDZ4NDvIfHlaCZC4T24lqPFhk5BXs+NiUyspS0H/MwfSUycnAiGfhHe2wvsdE7k7P+n3gaCB74aaAUnkBhfLAiVfHX1roHzxIhdgrWrq52ba998ZhdxG1e1qgBPDofbgx/aGFleMxnfie6WS6hHs=
    - secure: VVTbV74zv9+YNMwI7AcSNTVnBjqGne0r4VicGgx/n//fNtEo9rvUNFK6wmmSZF+jWKwo3Gp+T5K5Iw1ebvPHcffbc8olrdcGsT2mD6kATa4fMlO40b04AwsBR/0zphKsavhR8kSkULFcK5BClZTf//QMhoZXSbXnAl4ccAm71gUn9IuRWP7tecZPz1yGOu2l/X8nntSG8x48mnrIBOIW+q+pAkW6nGWYjrnl1+ftwcJNjqfK0fNCr2lKELkyS63+pjlfdGjhMD98NgsC7M6xHh5ZzMS3eZscCsVkGmhss1VO3l8XHIraQy8On8Dbr0UEygwxPtRStPp0JS7XH33ukcAHT6zfJJAJ5+7J4lOn1qe3apMqFwtOlMvLGRZ3tkxmDzb9PmOVBACXH/98PNfuQ/Xk6gjm8T8UiR6wgM+ZYOIubVXDE5yXz/Y+sxbekfhmXoId0qtLxnoO6ffgMoVW6yLrvjmhZ0N16SzoZukI1cssn6pl7r/CA+DCwRqDyS153A1B5zr6SJToq0gZvR4YxYptFRyMJDJaN3fUzIIrPe0Vykg8A0ZvAWPHk+JvRa+MclqvPfytutDwwI91OkNfirsH/la8L7h/L4pWggaI08qMOLi+3CrwN2yhcdFk3+uGjpSXWPCCP6/4ttBnxb8Wo2VvZ9/F5F31T5gw2Ebe8CI=
    - secure: rKbRAO/dHilEqPvjLeYvA7V4q75RjmqLLBzztndQSuPKxcBGFeLoTqKD+aDz/9HKfOz8eKc7Vd6ha8Acouki3fh1bQWwDynNO5nG1PHbEC0BIhCMo97dIy+dAqeoFKz37bqvjn/YUa/R9UJaYZQAqX16EAhgqqM1RSCHl66uHG0fjCfaKC8H4s3doeroGs+hl8xbYUkYaHl+EekNyek91NSIRKRjEIagVSghVPVQuirvb1L+sGrfFW8Wh1osKJysd9htejD9J16XNlHnfJXVb7OMDGyjQRiZYyvUn9EEnSMbD28GALltUbdCyvsZUFgonG7ewCFVFigKHijhSQCtmhk7p+LAvAtJqROD7vi8tY8AkAJypRQw0AEbZYFHZVoP5VJUxeSF9J787D/AmLjFGdNbNoYbubBQ428Q8nvaGNDCklHj69/A9xQejRppVuOZVFN7hp/tIbcy88glTPSVdk4j2QrhYt647LTuVByIAsYe07+1ShWFXa5Iec4s1LLdvsMVyMnNWuStCFj76aS/WEDP7bM1XSyykjsc4+y8fHIb9kdYKOaNTtF476t3tcH+++OKtjwFybPJAjDmXbLlimXsUMchKFQ9gSVB8P+1q/VWM2vh3TIKqMe5acTzTKGSZKEJVM2PD0q0PwbBq9pOUAWsfZ1DLbA2mOM3c158rd0=

services:
  - docker

before_install:
  - cp docker-compose.travis.yml docker-compose.yml
  - docker-compose up -d

script:
  - docker-compose run -e RAILS_ENV=test app bundle exec rake db:migrate
  - docker-compose run app bundle exec rake test

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - bash ./script/build/after_success
